name: Deploy on Main Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      # - name: Install dependencies
      #   run: npm install

      - name: Run deploy script
        run: |
          git config --global user.name "Ops Kivid"
          git config --global user.email "ops@kivid.com.br"

          # Create or switch to lib branch
          if git show-ref --quiet refs/remotes/origin/lib; then
            git checkout lib || git checkout -b lib origin/lib
          else
            git checkout -b lib
          fi

          # Update .gitignore
          echo "/node_modules" >> .gitignore
          echo "/stories" >> .gitignore
          echo "/public" >> .gitignore
          echo "/.vite" >> .gitignore
          echo "vite-env.d.ts" >> .gitignore
          echo "*.stories.ts" >> .gitignore
          echo "*.stories.tsx" >> .gitignore
          echo "App.tsx" >> .gitignore
          echo "main.tsx" >> .gitignore

          # Commit and push changes
          git rm -r --cached .
          git add -A
          git commit -m "Add .gitignore for lib branch"
          git push origin lib --force
