name: Deploy on Main Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Run deploy script
        run: |
          git config --global user.name "Ops Kivid"
          git config --global user.email "ops@kivid.com.br"
          git ls-remote --exit-code origin lib &> /dev/null
          if [ $? -eq 0 ]; then
            git push origin --delete lib
          fi
          git checkout -b lib
          echo "/node_modules" >> .gitignore
          echo "/stories" >> .gitignore
          echo "/public" >> .gitignore
          echo "/.vite" >> .gitignore
          echo "vite-env.d.ts" >> .gitignore
          echo "*.stories.ts" >> .gitignore
          echo "*.stories.tsx" >> .gitignore
          echo "App.tsx" >> .gitignore
          echo "main.tsx" >> .gitignore
          git rm -r --cached .
          git add -A
          git commit -m "Add .gitignore for lib branch"
          git push --set-upstream origin lib
